
Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  if ENV['FOLDER'] != nil
    config.vm.provision "file", source: ENV['FOLDER'], destination: "/home/vagrant/imported"
  end
end
